version: '3.8'

services:
  backend:
    build:
      context: ./ids_backend
      dockerfile: Dockerfile
    container_name: ids-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=ids_backend.settings
    volumes:
      - ./ids_backend/static/model:/app/static/model
    restart: always

  frontend:
    build:
      context: ./ids_frontend
      dockerfile: Dockerfile
    container_name: ids-frontend
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - backend
    restart: always

networks:
  default:
    name: ids-network
